-- Tabla de lookup nombre -> sexo para enriquecimiento de voters.sexo
-- Fuente: top 321 nombres mas frecuentes del padron TSE 2026
-- Script ETL: scripts/enrich_sexo.php

CREATE TABLE IF NOT EXISTS name_gender_lookup (
    first_name VARCHAR(60) NOT NULL,
    sex        ENUM('M','F','ND') NOT NULL,
    PRIMARY KEY (first_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO name_gender_lookup (first_name, sex) VALUES
-- Top 80 nombres mas frecuentes
('MARIA','F'),('JOSE','M'),('LUIS','M'),('ANA','F'),('CARLOS','M'),
('JUAN','M'),('JORGE','M'),('VICTOR','M'),('OSCAR','M'),('GERARDO','M'),
('MARIO','M'),('RAFAEL','M'),('MANUEL','M'),('DANIEL','M'),('LAURA','F'),
('MARCO','M'),('DAVID','M'),('MIGUEL','M'),('FRANCISCO','M'),('KEVIN','M'),
('ANDREA','F'),('CARMEN','F'),('ROSA','F'),('KARLA','F'),('KATHERINE','F'),
('ALEXANDER','M'),('ADRIANA','F'),('RONALD','M'),('JONATHAN','M'),('ANDRES','M'),
('KAREN','F'),('ESTEBAN','M'),('WILLIAM','M'),('MARVIN','M'),('MARTA','F'),
('FLOR','F'),('EDUARDO','M'),('XINIA','F'),('ALVARO','M'),('DIEGO','M'),
('DANIELA','F'),('ALEJANDRO','M'),('ELIZABETH','F'),('SILVIA','F'),('MICHAEL','M'),
('SANDRA','F'),('RICARDO','M'),('OLGA','F'),('MAURICIO','M'),('BRYAN','M'),
('KATTIA','F'),('JOSUE','M'),('JAVIER','M'),('SONIA','F'),('ADRIAN','M'),
('JESUS','M'),('EDWIN','M'),('JESSICA','F'),('EDGAR','M'),('PABLO','M'),
('DIANA','F'),('SERGIO','M'),('FERNANDO','M'),('ROBERTO','M'),('LUZ','F'),
('KIMBERLY','F'),('ERICK','M'),('WALTER','M'),('RANDALL','M'),('CAROLINA','F'),
('SEBASTIAN','M'),('EVELYN','F'),('CHRISTIAN','M'),('GABRIEL','M'),('ALEJANDRA','F'),
('JULIO','M'),('ALLAN','M'),('HENRY','M'),('GUSTAVO','M'),('SHIRLEY','F'),
-- Nombres 81-160
('STEVEN','M'),('WENDY','F'),('JENNIFER','F'),('ANGIE','F'),('JOHNNY','M'),
('GABRIELA','F'),('MONICA','F'),('NATALIA','F'),('CESAR','M'),('KENNETH','M'),
('CRISTIAN','M'),('ROGER','M'),('GUILLERMO','M'),('VALERIA','F'),('FABIAN','M'),
('MARIANA','F'),('TATIANA','F'),('FREDDY','M'),('MARCOS','M'),('MELISSA','F'),
('STEPHANIE','F'),('KAROL','F'),('GREIVIN','M'),('ANTHONY','M'),('ROXANA','F'),
('RODRIGO','M'),('JEAN','M'),('RODOLFO','M'),('BRANDON','M'),('LIGIA','F'),
('PATRICIA','F'),('CINDY','F'),('RAQUEL','F'),('MARITZA','F'),('ROY','M'),
('SOFIA','F'),('NICOLE','F'),('MARJORIE','F'),('REBECA','F'),('MINOR','M'),
('JENNY','F'),('GRETTEL','F'),('MARGARITA','F'),('ISABEL','F'),('JOHANNA','F'),
('PEDRO','M'),('ALBERTO','M'),('JACQUELINE','F'),('ANGEL','M'),('VIRGINIA','F'),
('HAZEL','F'),('BLANCA','F'),('YAMILETH','F'),('ANDREY','M'),('MARLENE','F'),
('MARCELA','F'),('ISAAC','M'),('SHARON','F'),('ALEXIS','M'),('YESENIA','F'),
('MIRIAM','F'),('MAYRA','F'),('JOHAN','M'),('VERONICA','F'),('GIOVANNI','M'),
('MARLON','M'),('PAOLA','F'),('ROLANDO','M'),('KARINA','F'),('INGRID','F'),
('NELSON','M'),('LEONARDO','M'),('ORLANDO','M'),('GENESIS','F'),('FRANKLIN','M'),
('VIVIANA','F'),('JASON','M'),('GERMAN','M'),('HECTOR','M'),('JOSELYN','F'),
-- Nombres 161-240
('YORLENY','F'),('PAULA','F'),('MARIANELA','F'),('JEANNETTE','F'),('OLMAN','M'),
('JAIRO','M'),('SARA','F'),('NANCY','F'),('KENDALL','M'),('YENDRY','F'),
('RUTH','F'),('ANTONIO','M'),('JIMENA','F'),('FABIOLA','F'),('JOSEPH','M'),
('MARIBEL','F'),('BRAYAN','M'),('ERIKA','F'),('MARTIN','M'),('DAMARIS','F'),
('IVANNIA','F'),('ERICKA','F'),('ROSIBEL','F'),('CHRISTOPHER','M'),('MARIELA','F'),
('HILDA','F'),('VILMA','F'),('ALEXANDRA','F'),('MAUREEN','F'),('ANGELA','F'),
('DAYANA','F'),('PRISCILLA','F'),('NURIA','F'),('HUGO','M'),('OMAR','M'),
('MICHELLE','F'),('HELLEN','F'),('CECILIA','F'),('SUSANA','F'),('GERALD','M'),
('JIMMY','M'),('JEFFRY','M'),('ENRIQUE','M'),('MELVIN','M'),('IVAN','M'),
('LIDIA','F'),('LILLIAM','F'),('JUSTIN','M'),('FIORELLA','F'),('VANESSA','F'),
('RIGOBERTO','M'),('PAMELA','F'),('JOSHUA','M'),('RAMON','M'),('ANGELICA','F'),
('LILLIANA','F'),('NORMA','F'),('GISELLE','F'),('FELIX','M'),('LORENA','F'),
('GRACE','F'),('RONNY','M'),('NIDIA','F'),('ALEX','M'),('AARON','M'),
('JUANA','F'),('ERIC','M'),('JEREMY','M'),('ALBA','F'),('DANNY','M'),
('IRENE','F'),('ALICIA','F'),('JEFFERSON','M'),('ALFREDO','M'),('DENNIS','M'),
('MELANY','F'),('CRISTOPHER','M'),('DOUGLAS','M'),('MARILYN','F'),('KRISTEL','F'),
-- Nombres 241-321
('MARISOL','F'),('YOLANDA','F'),('CRISTINA','F'),('GILBERTO','M'),('GLADYS','F'),
('LUCIA','F'),('ELIECER','M'),('ROCIO','F'),('VERA','F'),('YERLIN','F'),
('DAISY','F'),('OLGER','M'),('EMILY','F'),('SANTIAGO','M'),('ILEANA','F'),
('EMMANUEL','M'),('RAUL','M'),('RITA','F'),('GUISELLE','F'),('ASHLEY','F'),
('GILBERT','M'),('JORDAN','M'),('DYLAN','M'),('MAYELA','F'),('GLORIA','F'),
('JAIME','M'),('DENIS','M'),('TERESA','F'),('ALLISON','F'),('KEILYN','F'),
('FLORA','F'),('MARTHA','F'),('IRIS','F'),('JEISON','M'),('MERCEDES','F'),
('CLAUDIA','F'),('BRENDA','F'),('ALONSO','M'),('DANILO','M'),('ABIGAIL','F'),
('AXEL','M'),('KEYLOR','M'),('MOISES','M'),('ELENA','F'),('HERNAN','M'),
('ARIANA','F'),('ARIEL','M'),('SEIDY','F'),('FABIO','M'),('FANNY','F'),
('CYNTHIA','F'),('ARMANDO','M'),('ELIAS','M'),('FLORIBETH','F'),('HANNIA','F'),
('CLAUDIO','M'),('HILLARY','F'),('GLORIANA','F'),('LEONEL','M'),('GEINER','M'),
('YULIANA','F'),('LEIDY','F'),('WILSON','M'),('YADIRA','F'),('ALFONSO','M'),
('TERESITA','F'),('JAZMIN','F'),('MAIKOL','M'),('CAROL','F'),('JUNIOR','M'),
('JOHN','M'),('FELIPE','M'),('DORIS','F'),('VIVIAN','F'),('CATALINA','F'),
('CAMILA','F'),('LIDIETH','F'),('VICTORIA','F'),('ZAIDA','F'),('MARICELA','F'),
('TANIA','F'),('SANTOS','M'),('CINTHYA','F'),('FLORY','F'),('BEATRIZ','F'),
('ASHLY','F'),('WILBER','M'),('VALERY','F'),('DORA','F'),('ARTURO','M'),
('CRISTHIAN','M'),('ANDY','M'),('BYRON','M'),('MIREYA','F'),('EDDY','M'),
('LETICIA','F'),('SUSAN','F'),('EDITH','F'),('NOEMY','F'),('RUBEN','M'),
('DIDIER','M'),('JULIA','F'),('EMANUEL','M'),('LUISA','F'),('RANDY','M'),
('MELANIE','F'),('MARY','F'),('ADOLFO','M'),('ANABELLE','F'),('JULIAN','M'),
('DAGOBERTO','M'),('GRACIELA','F'),('ALEXA','F'),('MILENA','F'),('EMILCE','F'),
('AMANDA','F'),('MAINOR','M'),('KEYLIN','F'),('HEIDY','F'),('FRANCINI','F'),
('ALISON','F'),('XIOMARA','F'),('ARACELLY','F'),('IRMA','F'),('ELSA','F'),
('MANFRED','M'),('JOEL','M'),('EMILIA','F'),('RICHARD','M'),('ERNESTO','M'),
('AIDA','F'),('HAROLD','M'),('NORMAN','M'),('LEDA','F'),('ROBERT','M'),
('HELEN','F'),('GUIDO','M'),('LISBETH','F'),('OLDEMAR','M'),('FABRICIO','M'),
('FEDERICO','M'),('MARLEN','F'),('PRISCILA','F'),('GEOVANNY','M'),('HEINER','M'),
('CLARA','F'),('LIZBETH','F'),('IGNACIO','M'),('LOURDES','F'),('EFRAIN','M'),
('DINORAH','F'),('EUGENIA','F'),('BERNARDO','M'),('ISMAEL','M'),('CINTHIA','F'),
('ASDRUBAL','M'),('DILAN','M'),('NELLY','F'),('BERNAL','M'),('LIZETH','F');
